#!/bin/sh

filename="maker"
pathprefix=`echo ~wrc/bin`
outfile="tents"

if [ `basename -- $0` != "$filename" ] #file being sourced
	then
		( echo $PATH | grep -q "$pathprefix" ) || export PATH="$pathprefix":$PATH
		true #always succeed
	else
		allgood=true
		
		for filename in *.asm
			do
				if [ "$filename" != "*.asm" ]
					then
						$allgood && ( rasm "$filename" || allgood=false )
					else
						echo "No asm files found!"
						allgood=false
					fi
			done
		
		$allgood && ( rlink -o "${outfile}.out" *.obj || allgood=false )
		
		$allgood #return proper exit status
	fi
