#!/bin/sh

filename="maker"
pathprefix=`echo ~wrc/bin`
outfile="tents"

if [ `basename -- "$0"` != "$filename" ] #file being sourced
	then
		( echo $PATH | grep -q "$pathprefix" ) || export PATH="$pathprefix":$PATH
	else
		set -e
		
		for filename in *.asm
			do
				if [ "$filename" != "*.asm" ]
					then
						rasm "$filename"
					else
						echo "No asm files found!"
						false #bail out!
					fi
			done
		
		rlink -o "${outfile}.out" *.obj
	fi
